version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
            RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
      - 15672:15672

  pubsubsample.client:
    image: ${DOCKER_REGISTRY-}pubsubsampleclient
    build:
      context: .
      dockerfile: PubSubSample.Client/Dockerfile

  pubsubsample.service:
    image: ${DOCKER_REGISTRY-}pubsubsampleservice
    build:
      context: .
      dockerfile: PubSubSample.Service/Dockerfile

